// Data transcribed from pack_shop_draft.xlsx: Packs, Drop Rates, Tiers, Players.
export const GUIDE = {
  tiers: [
    {
      name: "Rookie",
      min: 55.0,
      max: 64.0,
      count: 6.0,
      sell: 25.0,
    },
    {
      name: "Club",
      min: 65.0,
      max: 69.0,
      count: 10.0,
      sell: 75.0,
    },
    {
      name: "Rare",
      min: 70.0,
      max: 74.0,
      count: 10.0,
      sell: 200.0,
    },
    {
      name: "Elite",
      min: 75.0,
      max: 81.0,
      count: 10.0,
      sell: 600.0,
    },
    {
      name: "Champion",
      min: 82.0,
      max: 85.0,
      count: 16.0,
      sell: 1500.0,
    },
    {
      name: "Legend",
      min: 86.0,
      max: 89.0,
      count: 10.0,
      sell: 3500.0,
    },
    {
      name: "Heroes",
      min: 84.0,
      max: 89.0,
      count: 10.0,
      sell: 7000.0,
    },
    {
      name: "Icon",
      min: 90.0,
      max: 97.0,
      count: 10.0,
      sell: 15000.0,
    },
    {
      name: "Mythic",
      min: 95.0,
      max: 97.0,
      count: 14.0,
      sell: 30000.0,
    },
    {
      name: "Glory",
      min: 94.0,
      max: 99.0,
      count: 8.0,
      sell: 60000.0,
    },
    {
      name: "Eternal",
      min: 99.0,
      max: 100.0,
      count: 8.0,
      sell: 150000.0,
    },
  ],
  packs: [
    {
      id: "bronze",
      name: "Bronze Pack",
      cost: 500.0,
      count: 3,
      odds: [45.0, 35.0, 15.0, 4.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
      description: "Independent tier rolls. Quick-sell values vary by rarity.",
    },
    {
      id: "silver",
      name: "Silver Pack",
      cost: 1500.0,
      count: 4,
      odds: [15.0, 35.0, 30.0, 15.0, 4.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
      description: "Independent tier rolls. Quick-sell values vary by rarity.",
    },
    {
      id: "gold",
      name: "Gold Pack",
      cost: 4000.0,
      count: 5,
      odds: [0.0, 15.0, 35.0, 30.0, 14.0, 5.0, 0.9, 0.1, 0.0, 0.0, 0.0],
      description: "Independent tier rolls. Quick-sell values vary by rarity.",
    },
    {
      id: "premium",
      name: "Premium Pack",
      cost: 10000.0,
      count: 5,
      odds: [0.0, 0.0, 20.0, 35.0, 25.0, 14.0, 4.0, 1.5, 0.5, 0.0, 0.0],
      description: "Independent tier rolls. Quick-sell values vary by rarity.",
    },
    {
      id: "ultimate",
      name: "Ultimate Pack",
      cost: 25000.0,
      count: 5,
      odds: [0.0, 0.0, 0.0, 22.0, 32.0, 25.0, 13.0, 6.0, 1.5, 0.4, 0.1],
      description: "Independent tier rolls. Quick-sell values vary by rarity.",
    },
    {
      id: "glory",
      name: "Glory Pack",
      cost: 75000.0,
      count: 3,
      odds: [0.0, 0.0, 0.0, 0.0, 10.0, 25.0, 25.0, 20.0, 12.0, 6.0, 2.0],
      description: "Independent tier rolls. Quick-sell values vary by rarity.",
    },
  ],
  players: [
    {
      name: "Benny Okoro",
      rarity: "Rookie",
      position: "GK",
      rating: 58,
    },
    {
      name: "Pip Hallowell",
      rarity: "Rookie",
      position: "DEF",
      rating: 60,
    },
    {
      name: "Tavi Rennick",
      rarity: "Rookie",
      position: "MID",
      rating: 62,
    },
    {
      name: "Cole Brannigan",
      rarity: "Rookie",
      position: "MID",
      rating: 61,
    },
    {
      name: "Jonas Pell",
      rarity: "Rookie",
      position: "FWD",
      rating: 63,
    },
    {
      name: "Dex Mulvaney",
      rarity: "Rookie",
      position: "DEF",
      rating: 56,
    },
    {
      name: "Milo Ashby",
      rarity: "Club",
      position: "GK",
      rating: 65,
    },
    {
      name: "Reed Hollis",
      rarity: "Club",
      position: "DEF",
      rating: 66,
    },
    {
      name: "Owen Tarrant",
      rarity: "Club",
      position: "MID",
      rating: 67,
    },
    {
      name: "Gus Penrose",
      rarity: "Club",
      position: "MID",
      rating: 66,
    },
    {
      name: "Lars Keating",
      rarity: "Club",
      position: "FWD",
      rating: 68,
    },
    {
      name: "Dane Whitcomb",
      rarity: "Club",
      position: "DEF",
      rating: 65,
    },
    {
      name: "Eli Sorrento",
      rarity: "Club",
      position: "MID",
      rating: 69,
    },
    {
      name: "Ravi Mehta",
      rarity: "Club",
      position: "FWD",
      rating: 67,
    },
    {
      name: "Tom Harker",
      rarity: "Club",
      position: "GK",
      rating: 67,
    },
    {
      name: "Noel Fairchild",
      rarity: "Club",
      position: "DEF",
      rating: 69,
    },
    {
      name: "Jasper Quill",
      rarity: "Rare",
      position: "GK",
      rating: 70,
    },
    {
      name: "Mateo Rinaldi",
      rarity: "Rare",
      position: "DEF",
      rating: 72,
    },
    {
      name: "Callum Drake",
      rarity: "Rare",
      position: "MID",
      rating: 73,
    },
    {
      name: "Sven Larkin",
      rarity: "Rare",
      position: "MID",
      rating: 71,
    },
    {
      name: "Kian Delaney",
      rarity: "Rare",
      position: "FWD",
      rating: 74,
    },
    {
      name: "Otis Brandl",
      rarity: "Rare",
      position: "DEF",
      rating: 70,
    },
    {
      name: "Rory Castellan",
      rarity: "Rare",
      position: "MID",
      rating: 72,
    },
    {
      name: "Amir Tahiri",
      rarity: "Rare",
      position: "FWD",
      rating: 72,
    },
    {
      name: "Wes Yarrow",
      rarity: "Rare",
      position: "GK",
      rating: 73,
    },
    {
      name: "Dmitri Bell",
      rarity: "Rare",
      position: "DEF",
      rating: 74,
    },
    {
      name: "Lukas Heron",
      rarity: "Elite",
      position: "GK",
      rating: 77,
    },
    {
      name: "Adrian Voight",
      rarity: "Elite",
      position: "DEF",
      rating: 79,
    },
    {
      name: "Nate Calder",
      rarity: "Elite",
      position: "MID",
      rating: 80,
    },
    {
      name: "Fabio Santoro",
      rarity: "Elite",
      position: "MID",
      rating: 78,
    },
    {
      name: "Jonah Pryce",
      rarity: "Elite",
      position: "FWD",
      rating: 81,
    },
    {
      name: "Leo Ashdown",
      rarity: "Elite",
      position: "DEF",
      rating: 76,
    },
    {
      name: "Marco Veltri",
      rarity: "Elite",
      position: "MID",
      rating: 77,
    },
    {
      name: "Ezra Kallen",
      rarity: "Elite",
      position: "FWD",
      rating: 79,
    },
    {
      name: "Piotr Zelenko",
      rarity: "Elite",
      position: "GK",
      rating: 75,
    },
    {
      name: "Cyril Maddox",
      rarity: "Elite",
      position: "DEF",
      rating: 78,
    },
    {
      name: "Rhys Calloway",
      rarity: "Champion",
      position: "FWD",
      rating: 85,
    },
    {
      name: "Mikael Dorne",
      rarity: "Champion",
      position: "MID",
      rating: 84,
    },
    {
      name: "Arlo Fenwick",
      rarity: "Champion",
      position: "DEF",
      rating: 84,
    },
    {
      name: "Zane Ivarsson",
      rarity: "Champion",
      position: "GK",
      rating: 83,
    },
    {
      name: "Pavel Draganov",
      rarity: "Champion",
      position: "MID",
      rating: 83,
    },
    {
      name: "Cato Whitlock",
      rarity: "Champion",
      position: "DEF",
      rating: 82,
    },
    {
      name: "Bastien Kroll",
      rarity: "Champion",
      position: "FWD",
      rating: 85,
    },
    {
      name: "Teo Marlowe",
      rarity: "Champion",
      position: "MID",
      rating: 85,
    },
    {
      name: "Hugo Lindahl",
      rarity: "Champion",
      position: "DEF",
      rating: 85,
    },
    {
      name: "Ismael Duarte",
      rarity: "Champion",
      position: "GK",
      rating: 84,
    },
    {
      name: "Felix Rourke",
      rarity: "Champion",
      position: "MID",
      rating: 84,
    },
    {
      name: "Anton Sevic",
      rarity: "Champion",
      position: "FWD",
      rating: 84,
    },
    {
      name: "Joaquin Maldrin",
      rarity: "Champion",
      position: "DEF",
      rating: 83,
    },
    {
      name: "Niall Pemberton",
      rarity: "Champion",
      position: "MID",
      rating: 83,
    },
    {
      name: "Stellan Voss",
      rarity: "Champion",
      position: "GK",
      rating: 82,
    },
    {
      name: "Kofi Adebayo",
      rarity: "Champion",
      position: "FWD",
      rating: 82,
    },
    {
      name: "Gabriel Ironside",
      rarity: "Legend",
      position: "GK",
      rating: 87,
    },
    {
      name: "Matthias Crowe",
      rarity: "Legend",
      position: "DEF",
      rating: 88,
    },
    {
      name: "Alessio Brambilla",
      rarity: "Legend",
      position: "MID",
      rating: 89,
    },
    {
      name: "Joel Hartwell",
      rarity: "Legend",
      position: "MID",
      rating: 87,
    },
    {
      name: "Rodrigo Estrada",
      rarity: "Legend",
      position: "FWD",
      rating: 89,
    },
    {
      name: "Anders Falk",
      rarity: "Legend",
      position: "DEF",
      rating: 86,
    },
    {
      name: "Kenji Sato",
      rarity: "Legend",
      position: "MID",
      rating: 88,
    },
    {
      name: "Bruno Calderon",
      rarity: "Legend",
      position: "FWD",
      rating: 88,
    },
    {
      name: "Tobias Wren",
      rarity: "Legend",
      position: "GK",
      rating: 86,
    },
    {
      name: "Yannick Roux",
      rarity: "Legend",
      position: "DEF",
      rating: 87,
    },
    {
      name: "Tomas Vreld",
      rarity: "Heroes",
      position: "FWD",
      rating: 89,
    },
    {
      name: "Kaito Marenz",
      rarity: "Heroes",
      position: "MID",
      rating: 88,
    },
    {
      name: "Luca Brandt",
      rarity: "Heroes",
      position: "DEF",
      rating: 88,
    },
    {
      name: "Dario Quellan",
      rarity: "Heroes",
      position: "MID",
      rating: 87,
    },
    {
      name: "Emeka Torvald",
      rarity: "Heroes",
      position: "MID",
      rating: 87,
    },
    {
      name: "Ivo Strand",
      rarity: "Heroes",
      position: "GK",
      rating: 86,
    },
    {
      name: "Nico Valdeur",
      rarity: "Heroes",
      position: "DEF",
      rating: 85,
    },
    {
      name: "Soren Aldric",
      rarity: "Heroes",
      position: "MID",
      rating: 85,
    },
    {
      name: "Marek Ostrava",
      rarity: "Heroes",
      position: "FWD",
      rating: 84,
    },
    {
      name: "Yusuf Karimov",
      rarity: "Heroes",
      position: "DEF",
      rating: 84,
    },
    {
      name: "Rafael Montclair",
      rarity: "Icon",
      position: "MID",
      rating: 97,
    },
    {
      name: "Anselmo Draven",
      rarity: "Icon",
      position: "FWD",
      rating: 96,
    },
    {
      name: "Viktor Halloran",
      rarity: "Icon",
      position: "DEF",
      rating: 95,
    },
    {
      name: "Enzo Barosso",
      rarity: "Icon",
      position: "MID",
      rating: 94,
    },
    {
      name: "Mateus Corbell",
      rarity: "Icon",
      position: "FWD",
      rating: 94,
    },
    {
      name: "Henrik Valstrom",
      rarity: "Icon",
      position: "GK",
      rating: 93,
    },
    {
      name: "Dmitri Kessler",
      rarity: "Icon",
      position: "FWD",
      rating: 92,
    },
    {
      name: "Leandro Ferraz",
      rarity: "Icon",
      position: "DEF",
      rating: 91,
    },
    {
      name: "Oskar Lindqvist",
      rarity: "Icon",
      position: "MID",
      rating: 91,
    },
    {
      name: "Tariq Benali",
      rarity: "Icon",
      position: "MID",
      rating: 90,
    },
    {
      name: "Lucian Vesper",
      rarity: "Mythic",
      position: "MID",
      rating: 97,
    },
    {
      name: "Oren Blackwood",
      rarity: "Mythic",
      position: "FWD",
      rating: 97,
    },
    {
      name: "Caspian Thorne",
      rarity: "Mythic",
      position: "DEF",
      rating: 96,
    },
    {
      name: "Alaric Sunderland",
      rarity: "Mythic",
      position: "GK",
      rating: 96,
    },
    {
      name: "Idris Moonfield",
      rarity: "Mythic",
      position: "MID",
      rating: 95,
    },
    {
      name: "Evander Cray",
      rarity: "Mythic",
      position: "FWD",
      rating: 95,
    },
    {
      name: "Magnus Ravenscroft",
      rarity: "Mythic",
      position: "MID",
      rating: 97,
    },
    {
      name: "Dorian Ashcombe",
      rarity: "Mythic",
      position: "DEF",
      rating: 97,
    },
    {
      name: "Elias Thornquist",
      rarity: "Mythic",
      position: "FWD",
      rating: 96,
    },
    {
      name: "Sebastian Wyndham",
      rarity: "Mythic",
      position: "MID",
      rating: 96,
    },
    {
      name: "Cyrus Valemont",
      rarity: "Mythic",
      position: "FWD",
      rating: 96,
    },
    {
      name: "Mikhail Stormvale",
      rarity: "Mythic",
      position: "GK",
      rating: 95,
    },
    {
      name: "Roland Eisenhart",
      rarity: "Mythic",
      position: "DEF",
      rating: 95,
    },
    {
      name: "Tobias Greymont",
      rarity: "Mythic",
      position: "MID",
      rating: 95,
    },
    {
      name: "Aurelio Zenith",
      rarity: "Glory",
      position: "MID",
      rating: 99,
    },
    {
      name: "Kaspar Nightingale",
      rarity: "Glory",
      position: "FWD",
      rating: 98,
    },
    {
      name: "Valen Ashgrove",
      rarity: "Glory",
      position: "MID",
      rating: 97,
    },
    {
      name: "Ibrahim Solari",
      rarity: "Glory",
      position: "DEF",
      rating: 96,
    },
    {
      name: "Matteo Crestfall",
      rarity: "Glory",
      position: "MID",
      rating: 96,
    },
    {
      name: "Lothar Emberg",
      rarity: "Glory",
      position: "GK",
      rating: 95,
    },
    {
      name: "Jericho Vale",
      rarity: "Glory",
      position: "DEF",
      rating: 95,
    },
    {
      name: "Santiago Dawnbridge",
      rarity: "Glory",
      position: "FWD",
      rating: 94,
    },
    {
      name: "Solomon Everhart",
      rarity: "Eternal",
      position: "MID",
      rating: 100,
    },
    {
      name: "Atlas Wraithmoor",
      rarity: "Eternal",
      position: "FWD",
      rating: 99,
    },
    {
      name: "Orion Vanterpool",
      rarity: "Eternal",
      position: "DEF",
      rating: 99,
    },
    {
      name: "Cassius Hollowell",
      rarity: "Eternal",
      position: "GK",
      rating: 99,
    },
    {
      name: "Raphael Stargazer",
      rarity: "Eternal",
      position: "FWD",
      rating: 100,
    },
    {
      name: "Gideon Ironvale",
      rarity: "Eternal",
      position: "DEF",
      rating: 100,
    },
    {
      name: "Maximilian Skyborne",
      rarity: "Eternal",
      position: "GK",
      rating: 100,
    },
    {
      name: "Phoenix Aldermoor",
      rarity: "Eternal",
      position: "MID",
      rating: 99,
    },
  ],
};
